# Site
name: 'NeonSec'
description: 'NeonSec is a Cyber Security Research Team based in India. We are a group of Cyber Security Enthusiasts who are passionate about Cyber Security and are always ready to learn new things. We are also a part of the Cyber Security Research Team at DedsecInside.'
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'neonsec'
email: 'thepsnarayanan@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    psn:
      name:           PSN
      site:           https://neonsec.in
      avatar:         assets/images/psn.jpeg
      bio:            "Hi, I am PSN, the author of TorBot. I am a Cyber Security Enthusiast and Founder of DedsecInside. I am also a member of the Cyber Security Research Team at NeonSec."
      email:          thepsnarayanan@gmail.com
      linkedin:       http://linkedin.com/in/0xpsn/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: psn
      avatar: /assets/images/psn.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]