# Site
name: 'NEONSEC'
description: 'NeonSec is a Cyber Security Research Team based in India. We are a group of Cyber Security and Tech Enthusiasts who are passionate about Technology and are always ready to learn new things.'
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'neonsec'
email: 'thepsnarayanan@gmail.com'
mailchimp-list: 'https://neonsec.us14.list-manage.com/subscribe/post?u=cbfb1a34b03f8e9fed9176ae9&amp;id=2c9c36e91d&amp;f_id=00d5ffe3f0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    psn:
      name:           PSN
      site:           https://github.com/psnappz
      avatar:         assets/images/psn.webp
      bio:            "Meet PSN, the Cyber Security Enthusiast and Founder of DedsecInside who created TorBot OSINT Tool. As a member of the esteemed NeonSec research team, he's dedicated to keeping us safe in the digital age."
      email:          thepsnarayanan@gmail.com
      linkedin:       http://linkedin.com/in/0xpsn/

    nathalie:
      name:           Natalie Williams
      site:           
      avatar:         assets/images/natalie.webp
      bio:            "Natalie is a professional software architect based in the UK with over five years of experience in the field. She is a security and technology enthusiast, always keeping up with the latest developments in the industry. With her expertise in software architecture and passion for technology, Natalie brings a unique perspective to her writing."
      email:          natalie.williams94@gmail.com
      linkedin:  

    alec:
      name:           Alec Sanderson
      site:           
      avatar:         assets/images/alec.webp
      bio:            "Alec is a professional Dota 2 gamer from the United States. He is an expert in the latest games and gaming technology, and is particularly interested in the advancements in virtual reality and augmented reality. In addition to his gaming career, Alec is also a VR and AR developer, constantly pushing the boundaries of what's possible in the gaming world. His blog is a great resource for anyone looking to stay up-to-date on the latest developments in gaming and technology."
      email:          alec.xxxxxx0@gmail.com
      linkedin:       
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: psn
      avatar: /assets/images/psn.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

google_analytics: G-87W04YL6MZ


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]