# Site
name: 'NeonSec'
description: 'NeonSec is a Cyber Security Research Team based in India. We are a group of Cyber Security and Tech Enthusiasts who are passionate about Technology and are always ready to learn new things.'
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'neonsec'
email: 'thepsnarayanan@gmail.com'
mailchimp-list: 'https://neonsec.us14.list-manage.com/subscribe/post?u=cbfb1a34b03f8e9fed9176ae9&amp;id=2c9c36e91d&amp;f_id=00d5ffe3f0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    psn:
      name:           PSN
      site:           https://github.com/psnappz
      avatar:         assets/images/psn.webp
      bio:            "Meet PSN, the Cyber Security Enthusiast and Founder of DedsecInside who created TorBot OSINT Tool. As a member of the esteemed NeonSec research team, he's dedicated to keeping us safe in the digital age."
      email:          thepsnarayanan@gmail.com
      linkedin:       http://linkedin.com/in/0xpsn/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: psn
      avatar: /assets/images/psn.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]